---
os: linux
dist: xenial

language: python
python:
  - 3.7
  - 3.8

install:
  - |
    pip3 install -r requirements.txt && \
    pip3 install -r test_requirements.txt && \
    pip3 install -e .

script:
  - python3 -m pytest -sv --cov=kickeststats --cov-fail-under=60
  - python3 -m flake8 --disable-noqa kickeststats
  - mypy kickeststats

deploy:
  provider: script
  skip_cleanup: true
  script: bash .travis/deploy.sh
  on:
    branch: main

